version: 2.2.0.{build}

image: Visual Studio 2017

build_script:
- ps: .\src\build.ps1 -Configuration Release

test_script:
- ps: .\src\UniversalDashboard.UITest\shebang.tests.ps1 -Release -Integration -Speed

artifacts:
- path: src/output